# Generated by Django 2.2.6 on 2019-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='emailufps',
        ),
        migrations.AlterField(
            model_name='propietario',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=15),
        ),
    ]
