# Generated by Django 2.2.6 on 2019-10-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20191024_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=15),
        ),
    ]
