# Generated by Django 2.2.6 on 2019-10-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20191024_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSexo',
            fields=[
                ('id_sexo', models.AutoField(max_length=1, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=15)),
            ],
        ),
    ]
