# Generated by Django 2.2.6 on 2019-10-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_tiposexo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoSexo',
        ),
    ]
