# Generated by Django 2.2.6 on 2019-10-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_delete_tiposexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
