# Generated by Django 2.2.6 on 2019-10-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_administrador_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
