# Generated by Django 2.2.6 on 2019-10-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_especie', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nom_raza', models.CharField(max_length=15)),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mascota.Especie')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=15)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=15)),
                ('edad', models.IntegerField()),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mascota.Especie')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Propietario')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mascota.Raza')),
            ],
        ),
    ]
