# Generated by Django 2.2.6 on 2019-10-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=15)),
                ('sexo', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mascota.Especie')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mascota.Raza')),
            ],
        ),
    ]
