# Generated by Django 2.2.6 on 2019-10-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('mascota', '0002_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Propietario'),
        ),
    ]
